name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Build linux
    runs-on: ['self-hosted', 'linux', 'images']

    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --prefix=$GITHUB_WORKSPACE/local
    - name: make
      run: make
    - name: make install
      run: make install
        
    - name: performance evaluation
      run: |
        mkdir mnt_after
        mkdir mnt_before
        sudo mount -r /home/user/images/after ./mnt_after
        sudo mount -r /home/user/images/before ./mnt_before
        ./local/bin/tsk_recover -r /home/user/images/after ./recover | column -t -s $'\t' > report.txt
        python3 analyze_recover.py ./mnt_before ./mnt_after ./recover > performance.txt
        
    - name: Upload a recovery report
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: report.txt
        
    - name: Upload a performance report
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: performance.txt
        
    - name: clean
      if: ${{ always() }}
      run: |
        sudo umount ./mnt_after
        sudo umount ./mnt_before
        
      
  build-windows:
    name: Build windows
    runs-on: ['self-hosted', 'windows']
    
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          JDK_HOME: 'C:\Program Files\Java\jdk-14.0.1'
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.com" .\win32\tsk-win.sln /Build "Debug_NoLibs|Win32"
      - name: check tsk
        shell: cmd
        run: .\win32\Debug_NoLibs\tsk_recover.exe -V
