name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: check tsk
      run: ./bin/tsk_recover -V
      
  build-windows:
    name: Build windows
    runs-on: ['self-hosted', 'windows']
    
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
          devenv .\win32\tsk-win.sln /Build "Debug_NoLibs|Win32" #/Project libtsk]
      - name: check tsk
        shell: cmd
        run: .\win32\Debug_NoLibs\tsk_recover.exe -V
