name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: make install
    - name: bootstrap
      run: ./bootstrap
    - name: sleuthkit
      run: sleuthkit
