name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --prefix=$GITHUB_WORKSPACE/local
    - name: make
      run: make
    - name: make install
      run: make install
    - name: check tsk
      run: |
        cd local
        ls -l
        cd bin
        ls -l
        ./tsk_recover -V
      
  build-windows:
    name: Build windows
    runs-on: ['self-hosted', 'windows']
    
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          JDK_HOME: 'C:\Program Files\Java\jdk-14.0.1'
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv" .\win32\tsk-win.sln /Build "Debug_NoLibs|Win32"
      - name: check tsk
        shell: cmd
        run: .\win32\Debug_NoLibs\tsk_recover.exe -V
